AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  workshop

Transform:
- AWS::Serverless-2016-10-31

Resources:
  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/getUserById.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 30
      Events:
        Api:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: GET
Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
